(unless (package-installed-p 'rainbow-identifiers)
  (package-install 'rainbow-identifiers)
  (package-refresh-contents))
(unless (package-installed-p 'telega)
  (package-install 'telega)
  (package-refresh-contents))
(unless (package-installed-p 'emojify)
  (package-install 'emojify)
  (package-refresh-contents))

(add-to-list 'load-path "/home/panthevm/.emacs.d/libraries/telega.el")
(add-to-list 'load-path "/home/panthevm/.emacs.d/libraries/visual-fill-column")
(require 'telega)
(require 'emojify)
(require 'visual-fill-column)
(setq emojify-emoji-set "emojione-v2-22")
(global-emojify-mode)

(setq telega-use-images t)
(setq telega-root-show-avatars t)
(setq telega-sticker-set-download t)
(setq telega-chat-show-deleted-messages-for '(not saved-messages))
(setq telega-sticker-animated-play t)
(setq telega-chat-button-brackets
      '(((type private)    "" "")
	((type basicgroup) "" "")
	((type supergroup) "" "")
	((type channel)    "" "")
	(all               "" "")))
(setq telega-filters-custom
      '(("Main" . main)))
